Email Popup UI Overhaul
nolan1299/csci-401-capstone pull request #9
Opened 2020-09-19 08:02 UTC by roopalkondepudi

There are a few nit-picky things I still need to figure out how to do - specifically, changing the default text.

See below for 'completed' product.

<img width="1048" alt="Screen Shot 2020-09-19 at 1 01 58 AM" src="https://user-images.githubusercontent.com/22573578/93662260-bbc82480-fa13-11ea-88df-0cb8d4ee8345.png">

2020-09-19 08:03 UTC, roopalkondepudi commented
I realized that in the process I somehow broke the send functionality... that will be fixed ASAP

2020-09-19 20:00 UTC, nolan1299 requested changes
just some leftover  debugging comments

2020-09-19 20:00 UTC, nolan1299 commented on letterOfRecGenerator/views/pages/recommender-dashboard.ejs
> +                            <!-- <button id = "Edit"> Edit </button> -->
comment D:

2020-09-19 20:00 UTC, nolan1299 commented on letterOfRecGenerator/public/css/recommender-dashboard.css
> +/* #template-select-placeholder #template-select-placeholder{
D:

2020-09-19 20:05 UTC, nolan1299 commented
also prob a good idea to squash some of the commits to keep login2 fresh and clean

2020-09-25 22:07 UTC, nolan1299 approved these changes

2020-09-25 22:07 UTC, merged